#!/bin/bash

#openssl req -new -newkey rsa:2048 -nodes -out cert.csr -keyout cert.key

#openssl genrsa -out cert.key
#openssl req -new -key cert.key -out cert.csr
#openssl req -x509 -days 365 -in cert.csr -key cert.key -out cert.crt

if [ ! -n "$1" ]; then
	echo "Usage: $0 {filename}"
	exit 1
fi

key=$1.key
pkey=$key.private


if [ ! -f "$pkey" ]; then
	echo "$pkey does not exists"
	exit 1
fi

openssl rsa -in $pkey -out $key
echo "Save $pkey's decrypted key to $key"

crt=$1.crt
bcrt=$crt.bak
ca=ca.pem
subca=sub.class1.server.ca.pem
startsslcerts=http://cert.startssl.com/certs/

if [ ! -f "$bcrt" ]; then
	echo "$bcrt does not exists"
	exit 1
fi

if [ ! -f "$ca" ]; then
	wget $startsslcerts$ca
fi

if [ ! -f "$subca" ]; then
	wget $startsslcerts$subca
fi

cat $bcrt $ca $subca > $crt
echo "Save $bcrt, $ca and $subca contents to $crt"
